Store/StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace StoreApp.Components
{
	public class ProductSummaryViewComponent : ViewComponent
	{
		private readonly IServiceManager _manager;
		public ProductSummaryViewComponent(IServiceManager manager)
		{
			_manager = manager;
		}
		public string Invoke() 
		{
			return _manager.ProductService.GetAllProducts(false).Count().ToString();
		}
	}
}

Store/StoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IServiceManager _serviceManager;
		public CategoryController(IServiceManager service)
		{
			_serviceManager = service;
		}
		public IActionResult Index()
        {
            var model = _serviceManager.CategoryService.GetAllCategories(false);
            return View(model);
        }
    }
}

Store/StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Controllers
{
	public class OrderController : Controller
	{
		private readonly IServiceManager _manager;
		private readonly Cart _cart;

		public OrderController(IServiceManager manager, Cart cart)
		{
			_manager = manager;
			_cart = cart;
		}

		[Authorize]
		public ViewResult Checkout() => View(new Order());

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Checkout([FromForm] Order order)
		{
			if(_cart.Lines.Count() == 0)
			{
				ModelState.AddModelError("","Sorry, your cart is empty.");
			}
			if(ModelState.IsValid)
			{
				order.Lines = _cart.Lines.ToArray();
				_manager.OrderService.SaveOrder(order);
				_cart.Clear();
				return RedirectToPage("/Complete", new {OrderId = order.OrderId});
			}
			else
			{
				return View();
			}
		}
	}
}

Store/StoreApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Entities.Models;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;
using Entities.RequestParameters;
using StoreApp.Models;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _serviceManager;

        public ProductController(IServiceManager service)
        {
            _serviceManager = service;
        }

        public IActionResult Index(ProductRequestParameters p)
        {
            var products = _serviceManager.ProductService.GetAllProductsWithDetails(p);
            var pagination = new Pagination()
            {
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _serviceManager.ProductService.GetAllProducts(false).Count()
            };
            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }
        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            var model = _serviceManager.ProductService.GetOneProduct(id, false);
            ViewData["Title"] = model?.ProductName;
            return View(model);
        }
    }
}

Store/StoreApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Brand - @ViewData["Title"]</title>
    <link rel="stylesheet" asp-append-version="true" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" asp-append-version="true" href="~/css/site.css" />
    <link rel="stylesheet" asp-append-version="true" href="~/lib/font-awesome/css/all.css" />
</head>

<body>
    <header>
        <partial name="_Navbar" />
        @RenderSection("Header",false)
    </header>
    <div class="container">
        <div>
            <partial name="_Notification" />
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>
        @RenderSection("Footer",false)
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts",required:false)
</body>

</html>

Store/StoreApp/Areas/Admin/Views/Shared/_Navbar.cshtml
<nav class="navbar bg-dark border-bottom border-body  navbar-expand-md" data-bs-theme="dark">
	<div class="container">
		<a class="navbar-brand" href="/">Admin</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
				aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse d-md-inline-flex justify-content-between" id="navbarNav">
			<ul class="navbar-nav flex-grow-1">
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" asp-controller="Dashboard" asp-action="Index">
						<i class="fa-solid fa-house"></i>
						Dashboard
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" asp-controller="Product" asp-action="Index">Products (@await Component.InvokeAsync("ProductSummary"))</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" asp-controller="Category" asp-action="Index">Categories</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" asp-controller="Order" asp-action="Index">Orders</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" asp-controller="Role" asp-action="Index">Roles</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" asp-controller="User" asp-action="Index">Users</a>
				</li>
				@* <li class="nav-item">
				<a class="nav-link disabled" aria-disabled="true">Disabled</a>
				</li> *@
			</ul>
			<ul class="navbar-nav">
				<li class="nav-item">
					<a target="_blank" class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
						<i class="fa-solid fa-globe"></i>
						Web</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">
						<i class="fa-solid fa-right-from-bracket"></i>
						Logout</a>
				</li>
			</ul>
		</div>
	</div>
</nav>